version: "3.9"

services:
    web:
        image: charts
        build: 
            context: ./client
        ports:
            - 3001:3000
        environment: 
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - './client:/app'
            - '/app/node_modules'
    tyson:
        image: tyson
        build: 
            context: ./server
        command: /bin/bash -c "exec node_modules/.bin/nodemon -L src/index.js"
        ports: 
            - 8080:8080
        volumes:
            - ./server/src:/var/www/app/src
    # registry:
    #     volumes

# volumes:

# secrets: